# Generated by Django 2.2.7 on 2019-12-10 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191210_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 5, 47, 34, 981938)),
        ),
    ]
